source 'http://rubygems.org'

gem 'builder',                '~> 3.2.2'
gem 'middleman',              '~> 3.4.1'
gem 'middleman-autoprefixer', '~> 2.6.1'
gem 'middleman-blog',         '~> 3.5.3'
gem 'middleman-deploy',       '~> 1.0.0'
gem 'middleman-livereload',   '~> 3.4.5'
gem 'middleman-minify-html',  '~> 3.4.1'
gem 'nokogiri',               '~> 1.6.6.2'
gem 'redcarpet',              '~> 3.3.2'
