source 'http://rubygems.org'

gem 'builder',                '~> 3.2.2'
gem 'middleman',              '~> 4.1.11'
gem 'middleman-blog',         '~> 4.0.1'
gem 'middleman-deploy',       '~> 2.0.0.pre.alpha'
gem 'middleman-livereload',   '~> 3.4.6'
gem 'middleman-minify-html',  '~> 3.4.1'
gem 'middleman-sprockets',    '~> 4.1.0'
gem 'nokogiri',               '~> 1.6.8.1'
gem 'redcarpet',              '~> 3.3.4'
